sources:
  - name: Kier Davis
    sources:
      - twitter/kierdavis
      - delicious/kierdavis
  
  - name: Ian Davis
    sources:
      - twitter/iand
      - pinboard/iand
      - feed/blog.iandavis.com/feed/
  
  - name: Leigh Dodds
    sources:
      - twitter/ldodds
      - delicious/ldodds
  
  - name: Rob Styles
    sources:
      - twitter/mmmmmrob
      - feed/dynamicorange.com/feed/
  
  - name: Malcolm Landon
    sources:
      - twitter/malcyL
      - feed/malcolmlandon.wordpress.com/feed/
  
  - name: Sam Tunnicliffe
    sources:
      - twitter/beobal
      - feed/www.beobal.com/blog/feed
  
  - name: Ian Corns
    sources:
      - twitter/TheAgileAnalyst
      - feed/www.blogger.com/feeds/9501182/posts/default
  
  - name: Andrew Bate
    sources:
      - twitter/AndrewBate
      - feed/www.astilla.co.uk/blog/feed/
  
  - name: Keith Alexander
    sources:
      - twitter/keithalexander
  
  - name: Nadeem Shabir
    sources:
      - twitter/kiyanwang
      - feed/www.virtualchaos.co.uk/blog/feed/atom/
  
  - name: Justin Leavesley
    sources:
      - twitter/justinleavesley
      - feed/www.justinleavesley.com/journal/rss.xml
  
  - name: Ross Singer
    sources:
      - twitter/rsinger
      - feed/dilettantes.code4lib.org/blog/feed/
  
  - name: Chris Clarke
    sources:
      - twitter/robotrobot
      - feed/slashdotrobot.wordpress.com/feed/
  
  - name: Michael Fitzmaurice
    sources:
      - twitter/mickyfitz
  
  - name: Julian Higman
    sources:
      - twitter/jhigman
      - feed/julianhigman.com/blog/feed/
  
  - name: Danisha Bathia
    sources:
      - twitter/kukibee
  
  - name: Chris Waring
    sources:
      - twitter/cwaring
  
  - name: Laurian Gridinoc
    sources:
      - twitter/gridinoc
  
  - name: Tom Heath
    sources:
      - twitter/tommyH
  
  - name: Alan Dix
    sources:
      - twitter/alandix
  
  - name: Mark Bush
    sources:
      - twitter/Onkloud9
  
  - name: Rhys Wilkins
    sources:
      - twitter/mauvedeity
  
  - name: Dave Whitehouse
    sources:
      - twitter/daveiw
      - feed/blog.jsdi.co.uk/?feed=rss2
  
  - name: Richard Francis
    sources:
      - twitter/rich_francis
  
  - name: Richard Wallis
    sources:
      - twitter/rjw
      - feed/itoccurs.wordpress.com/feed/
  
  - name: Matt Moran
    sources:
      - feed/www.blogger.com/feeds/7399594943995830623/posts/default
  
  - name: Tim Hodson
    sources:
      - twitter/tim_hodson
      - feed/informationtakesover.co.uk/feed/
  
  - name: Zach Beauvais
    sources:
      - twitter/zbeauvais
      - feed/feeds.feedburner.com/ZachBeauvais
